modLoader = "javafml"
loaderVersion = "[46,)"
license = "GNU LGPL 3.0"
[[mods]]
modId = "ssdanmaku"
version = "${file.jarVersion}"
displayName = "ServersideDanmaku"
authors = "Tapio"
credits = "Thanks to TartaricAcid's origin project BakaDanmaku"
description = '''

'''